
CREATE TABLE IF NOT EXISTS public.bird
(
id serial NOT NULL,
cycle_id integer NOT NULL DEFAULT 0,
neural_network bytea NOT NULL DEFAULT '',
CONSTRAINT bird_pkey PRIMARY KEY (id),
CONSTRAINT bird_cycle_id_fkey FOREIGN KEY (cycle_id)
    REFERENCES public.cycle (id) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE CASCADE
)
WITH (
OIDS=FALSE
);
ALTER TABLE public.bird OWNER TO postgres;

COMMENT ON TABLE public.bird IS 'Stores the game cycle infomrations';
COMMENT ON COLUMN public.bird.id IS 'ID, generated by sequence';
COMMENT ON COLUMN public.bird.cycle_id IS 'Foreign key to the cycle table';
COMMENT ON COLUMN public.bird.neural_network IS 'The neural network of the bird';