CREATE TABLE IF NOT EXISTS public.cycle
(
id serial NOT NULL,
parent_id integer DEFAULT 0,
sum_fitness integer NOT NULL DEFAULT 0,
game_id integer NOT NULL DEFAULT 0,
parameters text NOT NULL DEFAULT '',
CONSTRAINT cycle_pkey PRIMARY KEY (id),
CONSTRAINT cycle_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES public.cycle (id) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE CASCADE
)
WITH (
OIDS=FALSE
);
ALTER TABLE public.cycle OWNER TO postgres;

COMMENT ON TABLE public.cycle IS 'Stores the game cycle informations';
COMMENT ON COLUMN public.cycle.id IS 'ID, generated by sequence';
COMMENT ON COLUMN public.cycle.parent_id IS 'Foreign key to this table, stores the first cycle of the gouped generations';
COMMENT ON COLUMN public.cycle.sum_fitness IS 'The sum fitness of the generation in this cycle';
COMMENT ON COLUMN public.cycle.parameters IS 'The running parameters';

CREATE UNIQUE INDEX IF NOT EXISTS cycle_cycle_parent_idx
ON public.cycle
USING btree
(id, parent_id);

INSERT INTO public.cycle (id, parent_id)
SELECT 0, 0
WHERE NOT EXISTS (SELECT 1 FROM public.cycle WHERE id = 0 AND parent_id = 0);