CREATE TABLE IF NOT EXISTS public.fitness
(
id serial NOT NULL,
cycle_id integer NOT NULL DEFAULT 0,
bird_id integer NOT NULL DEFAULT 0,
fitness_score integer NOT NULL DEFAULT 0,
CONSTRAINT fitness_pkey PRIMARY KEY (id),
CONSTRAINT fitness_cycle_id_fkey FOREIGN KEY (cycle_id)
    REFERENCES public.cycle (id) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE CASCADE,
CONSTRAINT fitness_bird_id_fkey FOREIGN KEY (bird_id)
    REFERENCES public.bird (id) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE CASCADE
)
WITH (
OIDS=FALSE
);
ALTER TABLE public.fitness OWNER TO postgres;

COMMENT ON TABLE public.fitness IS 'Stores the fitness infomrations';
COMMENT ON COLUMN public.fitness.id IS 'ID, generated by sequence';
COMMENT ON COLUMN public.fitness.cycle_id IS 'Foreign key to the cycle table';
COMMENT ON COLUMN public.fitness.bird_id IS 'Foreign key to the bird table';
COMMENT ON COLUMN public.fitness.fitness_score IS 'The fitness of the bird';